### ISSUE TITLE
The IDE should be told the source level should use Java 11 or lower syntax

### ISSUE THREAD

**Issue by craigmit** [NaluKit/gwt-maven-springboot-archetype#6]
The line:
```
<maven.compiler.source>17</maven.compiler.source>
```
https://github.com/NaluKit/gwt-maven-springboot-archetype/blob/main/modular-springboot-webapp/src/main/resources/archetype-resources/pom.xml#L15

Should be:
```
<maven.compiler.source>11</maven.compiler.source>
```

This is because GWT can only compile from Java 11 or lower syntax.

We can add:
```
<properties>
	<maven.compiler.source>17</maven.compiler.source> <!-- The server can use Java 17 syntax -->
</properties>
```
here https://github.com/NaluKit/gwt-maven-springboot-archetype/blob/main/modular-springboot-webapp/src/main/resources/archetype-resources/__rootArtifactId__-server/pom.xml#L14 to allow the server module to use Java 17 syntax.

**Comment by FrankHossfeld** [comment]
@craigmit something nice for a first PR ... :-)

**Comment by craigmit** [comment]
> @craigmit something nice for a first PR ... :-)

Ha, yep.  I need to figure out how to run the tests on my PC, to make sure I don't break anything, then I'll raise a PR.  🙂

@FrankHossfeld  I assume it's `mvn verify` to run the tests?  I've updated the resources in main and test, but it thinks they're different:
```
Archetype IT 'basic-webapp' failed: Some content are not equals
```
They look the same to me (with the top level pom having the extra blank lines).  I'm wondering if the whitespace is different or something.  Any ideas?  Thanks.

**EDIT:** 
It was whitespace.  The blank lines needed spaces.

PR raised:  https://github.com/NaluKit/gwt-maven-springboot-archetype/pull/8

Disclaimer:  The instructions "mvn archetype:generate with HEAD-SNAPSHOT" didn't work, as Maven complains it doesn't exist.  I think I need to install it first, or something like that.  At this point, I'm taking a gamble my change will just work.

Cheers.

**Comment by FrankHossfeld** [comment]
Thanks for supporting!

**Comment by FrankHossfeld** [comment]
Done
