### ISSUE TITLE
Serialization policy error is logged on first RPC call

### ISSUE THREAD

**Issue by craigmit** [NaluKit/gwt-maven-springboot-archetype#7]
When you run the app, the first time you press the "Send" button (so it does it's first RPC call), the following error is logged to the server:
```
INFO: com.mycompany.mywebapp.GreetingServiceImpl: ERROR: The serialization policy file '/mywebapp/469F8017688391FF4CD79514A6FCF659.gwt.rpc' was not found; did you forget to include it in this deployment?
Feb 24, 2024 6:52:41 PM org.apache.catalina.core.ApplicationContext log
INFO: com.mycompany.mywebapp.GreetingServiceImpl: WARNING: Failed to get the SerializationPolicy '469F8017688391FF4CD79514A6FCF659' for module 'http://localhost:8080/mywebapp/'; a legacy, 1.3.3 compatible, serialization policy will be used.  You may experience SerializationExceptions as a result.
```

The RPC call still works, but this error shouldn't occur.

Notes:
* This doesn't happen when pressing the "Send" button with the https://github.com/tbroyer/gwt-maven-archetypes generated code.
* If you try to access the `/mywebapp/xxx.gwt.rpc` file from the browser, you can.
* It's odd how it's an INFO log in GreetingServiceImpl, which then says "ERROR".

**Comment by FrankHossfeld** [comment]
I have stopped using RPC for over 8 years. So, someone with more experience (with RPC) would be highly welcome.

**Comment by craigmit** [comment]
This has been fixed with https://github.com/NaluKit/gwt-maven-springboot-archetype/pull/12  Thanks!
