### ISSUE TITLE
Unnecessary compile args

### ISSUE THREAD

**Issue by craigmit** [NaluKit/gwt-maven-springboot-archetype#9]
What does the following do:
```
<compilerArgs>
  <arg>-gen</arg>
  <arg>${basedir}/target/gwt/gen</arg>
</compilerArgs>
```
?

Found here:
- https://github.com/NaluKit/gwt-maven-springboot-archetype/blob/main/modular-springboot-webapp/src/main/resources/archetype-resources/__rootArtifactId__-client/pom.xml#L47C11-L50C26
- https://github.com/NaluKit/gwt-maven-springboot-archetype/blob/main/clean-modular-springboot-webapp/src/main/resources/archetype-resources/__rootArtifactId__-client/pom.xml#L47

If I remove it, it doesn't seem to affect anything.

**Comment by FrankHossfeld** [comment]
Well, in case it does something, you should see a 'gwt/gen'-folder in the target directory containing the generated sources from GWT.

**Comment by craigmit** [comment]
Apologies, you're correct.  Seems like it gives you the RPC generated code.  Thanks.
![image](https://github.com/NaluKit/gwt-maven-springboot-archetype/assets/16993010/6e419749-0060-4b97-a91c-10a925b11b7d)
